library(data.table)
library(ggplot2)
library(tidyverse)
library(rstatix)
library(ggpubr)
library(ggfortify)

###########################################################################
##### data loading and filtering
#### these are files generated by modkit pileup
setwd("")
ecoli_m4C_position <- fread("ecoli_condition_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
ecoli_m5C_position <- fread("ecoli_condition_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
ecoli_m6A_position <- fread("ecoli_condition_primary_pileup_combine_m6a.bed",sep="\t", header=TRUE)

ecoli_m4C_position_filter <- ecoli_m4C_position[ecoli_m4C_position$valid_coverage>=20,]
ecoli_m6A_position_filter <- ecoli_m6A_position[ecoli_m6A_position$valid_coverage>=20,]
ecoli_m5C_position_filter <- ecoli_m5C_position[ecoli_m5C_position$valid_coverage>=20,]

options(scipen=999)

rm(ecoli_m4C_position, ecoli_m5C_position, ecoli_m6A_position)

ecoli_m6A_position_filter$modified_base_code[ecoli_m6A_position_filter$modified_base_code=="a"] <- "m6A" 
ecoli_m6A_position_filter <- ecoli_m6A_position_filter%>%
  subset(modified_base_code=="m6A")
ecoli_m4C_position_filter$modified_base_code[ecoli_m4C_position_filter$modified_base_code=="21839"] <- "m4C" 
ecoli_m4C_position_filter <- ecoli_m4C_position_filter%>%
  subset(modified_base_code=="m4C")
ecoli_m5C_position_filter$modified_base_code[ecoli_m5C_position_filter$modified_base_code=="m"] <- "m5C" 
ecoli_m5C_position_filter <- ecoli_m5C_position_filter%>%
  subset(modified_base_code=="m5C")

ecoli_4mC_5mC_6mA_position_combine <- rbind(ecoli_m5C_position_filter, ecoli_m4C_position_filter, ecoli_m6A_position_filter) %>%
  mutate(genus="Escherichia")

setDT(ecoli_4mC_5mC_6mA_position_combine)

####################################################################################
#### funtions blocks
### PCA
summary_table <- function(combine_table){
  combine_summary <- combine_table[, .(mean_modified_number = mean(modified_number),
                                       mean_modified_fraction = mean(modified_number/valid_coverage)), 
                                   by = .(genus, chrom, start, end, modified_base_code, strand, phase, condition, replicate)]
  combine_summary <- as.data.frame(combine_summary)
  combine_summary$specific_id <- paste(combine_summary$chrom, combine_summary$end, combine_summary$strand, combine_summary$modified_base_code, sep="_")
  return(combine_summary)
}

summary_table_wider <- function(combine_summary){
  combine_summary_wider <- combine_summary %>%
    pivot_wider(names_from = specific_id, values_from = mean_modified_fraction, id_cols = c(phase, condition, replicate))
  ### add row names and convert dataframe to matrix to accelerate the calculation
  combine_summary_wider <- as.data.frame(combine_summary_wider)
  
  return(combine_summary_wider)
}

summary_cor_table_na_remove <- function(combine_summary_wider){
  combine_summary_cor_table <- combine_summary_wider[, !(names(combine_summary_wider) %in% c("phase", "replicate", "condition"))]
  combine_summary_cor_table <- as.matrix(combine_summary_cor_table)
  combine_summary_cor_table <- as.data.frame(combine_summary_cor_table)
  combine_summary_cor_table_clean <- Filter(function(x) all(!is.na(x)), combine_summary_cor_table)
  combine_summary_cor_table_clean_numeric <- as.data.frame(lapply(combine_summary_cor_table_clean, function(x) as.numeric(as.character(x))))
  return(combine_summary_cor_table_clean_numeric)
}

removeZeroVar2 <- function(df){
  # Convert all columns to numeric
  df_numeric <- as.data.frame(lapply(df, function(x) as.numeric(as.character(x))))
  # Keep only columns with more than 1 unique value (i.e., with variance)
  df_numeric <- df_numeric[, sapply(df_numeric, function(x) length(unique(x[!is.na(x)])) > 1)]
  return(df_numeric)
}

summary_wider_clean <- function(combine_summary_wider, summary_cor_table_clean){
  phase_replicate_id <- combine_summary_wider[, (names(combine_summary_wider) %in% c("phase", "replicate", "condition")), drop = FALSE]
  combine_summary_wider_clean <- cbind(phase_replicate_id, summary_cor_table_clean)
}

### t-SNE
## summary generation function
summary_generation_replicate <- function(depth_methyl_phase){
  
  depth_methyl_phase[, modified_fraction := modified_number / valid_coverage]
  
  depth_methyl_phase$specific_id <- paste(depth_methyl_phase$chrom, depth_methyl_phase$end, 
                                          depth_methyl_phase$strand, depth_methyl_phase$modified_base_code, sep="_")
  return(depth_methyl_phase)
}

## function to generate correlation matrix
corr_table_generate_replicate <- function(data_frame_summary){
  
  ### select the phase status
  depth_methylation_summary_wider <- data_frame_summary %>%
    pivot_wider(names_from = specific_id, values_from = modified_fraction, id_cols = c(phase, condition, replicate)) %>%
    mutate(condition_replicate=paste(condition, phase, replicate, sep="_"))
  
  ### add row names and convert dataframe to matrix to accelerate the calculation
  depth_methylation_summary_wider <- as.data.frame(depth_methylation_summary_wider)
  
  rownames(depth_methylation_summary_wider) <- depth_methylation_summary_wider[,"condition_replicate"]
  depth_methylation_summary_table <- depth_methylation_summary_wider[, !(names(depth_methylation_summary_wider) %in% c("condition_replicate"))]

  depth_methylation_summary_table <- Filter(function(x) all(!is.na(x)), depth_methylation_summary_table)
  return(depth_methylation_summary_table)
}

####################################################################################
### PCA
ecoli_4mC_5mC_6mA_position_combine_summary <- summary_table(ecoli_4mC_5mC_6mA_position_combine)
ecoli_4mC_5mC_6mA_position_combine_summary_table_wider <- summary_table_wider(ecoli_4mC_5mC_6mA_position_combine_summary)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table <- summary_cor_table_na_remove(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean <- removeZeroVar2(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table)
ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean <- summary_wider_clean(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider, ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean)
ecoli_methyl_pca_res <- prcomp(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean, scale. = T)

name_change_list <- list("37_degree"="37", "42_degree"="42", "acetic_acid"="ACE", "acetic_reverse"="RE", "3_Nacl"="TNA", "paraffin"="PA")
name_change_list_unlist <- unlist(name_change_list)
ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean$condition_short <- name_change_list_unlist[ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean$condition]

### t-SNE
ecoli_methyl_condition_combine_summary <- summary_generation_replicate(ecoli_4mC_5mC_6mA_position_combine)
ecoli_methyl_corr_table <- corr_table_generate_replicate(ecoli_methyl_condition_combine_summary)

condition_data_tsne <- tibble(perplexities = c(2, 4, 6, 8, 10, 11), seed=c(1727, 1727, 1727, 1727, 1727, 1727))
condition_data_tsne <- condition_data_tsne %>% 
  mutate(
    TSNE = map2(perplexities, seed, ~{
      set.seed(.y)
      Rtsne(as.matrix(ecoli_methyl_corr_table[,-c(1:3)]), check_duplicates = FALSE, dims=3, PCA=F, theta=0.0, perplexity=.x, max_iter=2000)}))

for (i in 1:nrow(condition_data_tsne)){
  x = condition_data_tsne$perplexities[[i]]
  assign(paste0("tsne_perplex_", x),
         tibble(
           x = condition_data_tsne$TSNE[[i]]$Y[,1],
           y = condition_data_tsne$TSNE[[i]]$Y[,2],
           z = condition_data_tsne$TSNE[[i]]$Y[,3],
           perplexity = condition_data_tsne$perplexities[[i]],
           condition = ecoli_methyl_corr_table$condition_short,
           condition_alt = ecoli_methyl_corr_table$condition_alt,
           replicate=ecoli_methyl_corr_table$replicate,
           phase=ecoli_methyl_corr_table$phase
         )
  )
}

####################################################################################
#### visualization
### PCA
autoplot(ecoli_methyl_pca_res, data=ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean, 
         colour = "condition_short", size=3, shape = "phase", alpha=0.9) +
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  scale_shape_manual("", breaks = c("exponential", "stationary"),
                     values = c(16, 17)) + 
  labs(shape="Phase", colour="Condition") + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.position="none") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

### t-SNE
ggplot(tsne_perplex_6, aes(x=y, y=z, color=condition, label=replicate, shape=phase)) + 
  geom_point(size=3, alpha=0.85) +
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  theme_light() +
  labs(x="t-SNE2", y="t-SNE3", shape="Phase") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        legend.position = "none") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))
