library(data.table)
library(ggplot2)
library(tidyverse)
library(rstatix)
library(ggpubr)
library(deeptime)
library(patchwork)
library(ggfortify)
library(Rtsne)
library(cowplot)

###########################################################################
###### read files
##### these are the files generated by modkit pileup
setwd("")
ecoli_condition_motif <- fread("ecoli_condition_pileup_motif_focus_combine.bed", sep="\t", header = T)
options(scipen=999)

ecoli_condition_motif_filter <- ecoli_condition_motif[ecoli_condition_motif$valid_coverage>=20,]

###########################################################################
###### functions blocks
##### PCA functions
summary_table <- function(combine_table){
  combine_summary <- combine_table[, .(mean_modified_number = mean(modified_number),
                                       mean_modified_fraction = mean(modified_number/valid_coverage)), 
                                   by = .(chrom, start, end, modified_base_code, strand, condition_short, phase, replicate)]
  combine_summary <- as.data.frame(combine_summary)
  combine_summary$specific_id <- paste(combine_summary$chrom, combine_summary$end, combine_summary$strand, combine_summary$modified_base_code, sep="_")
  return(combine_summary)
}

summary_table_wider <- function(combine_summary){
  combine_summary_wider <- combine_summary %>%
    pivot_wider(names_from = specific_id, values_from = mean_modified_fraction, id_cols = c(replicate, condition_short, phase))
  ### add row names and convert dataframe to matrix to accelerate the calculation
  combine_summary_wider <- as.data.frame(combine_summary_wider)
  
  return(combine_summary_wider)
}

summary_cor_table_na_remove <- function(combine_summary_wider){
  combine_summary_cor_table <- combine_summary_wider[, !(names(combine_summary_wider) %in% c("condition_short", "phase", "replicate"))]
  combine_summary_cor_table <- as.matrix(combine_summary_cor_table)
  combine_summary_cor_table <- as.data.frame(combine_summary_cor_table)
  combine_summary_cor_table_clean <- Filter(function(x) all(!is.na(x)), combine_summary_cor_table)
  combine_summary_cor_table_clean_numeric <- as.data.frame(lapply(combine_summary_cor_table_clean, function(x) as.numeric(as.character(x))))
  return(combine_summary_cor_table_clean_numeric)
}

removeZeroVar2 <- function(df){
  # Convert all columns to numeric
  df_numeric <- as.data.frame(lapply(df, function(x) as.numeric(as.character(x))))
  # Keep only columns with more than 1 unique value (i.e., with variance)
  df_numeric <- df_numeric[, sapply(df_numeric, function(x) length(unique(x[!is.na(x)])) > 1)]
  return(df_numeric)
}

summary_wider_clean <- function(combine_summary_wider, summary_cor_table_clean){
  phase_replicate_id <- combine_summary_wider[, (names(combine_summary_wider) %in% c("condition_short", "phase", "replicate")), drop = FALSE]
  combine_summary_wider_clean <- cbind(phase_replicate_id, summary_cor_table_clean)
}

##### t-SNE functions
summary_generation_replicate <- function(depth_methyl_phase){
  
  depth_methyl_phase[, modified_fraction := modified_number / valid_coverage]
  
  depth_methyl_phase$specific_id <- paste(depth_methyl_phase$chrom, depth_methyl_phase$end, 
                                          depth_methyl_phase$strand, depth_methyl_phase$modified_base_code, sep="_")
  return(depth_methyl_phase)
}

corr_table_generate_replicate <- function(data_frame_summary){
  
  ### select the phase status
  depth_methylation_summary_wider <- data_frame_summary %>%
    pivot_wider(names_from = specific_id, values_from = modified_fraction, id_cols = c(phase, condition_short, replicate)) %>%
    mutate(condition_replicate=paste(condition_short, phase, replicate, sep="_"))
  
  ### add row names and convert dataframe to matrix to accelerate the calculation
  depth_methylation_summary_wider <- as.data.frame(depth_methylation_summary_wider)
  
  rownames(depth_methylation_summary_wider) <- depth_methylation_summary_wider[,"condition_replicate"]
  depth_methylation_summary_table <- depth_methylation_summary_wider[, !(names(depth_methylation_summary_wider) %in% c("condition_replicate"))]

  depth_methylation_summary_table <- Filter(function(x) all(!is.na(x)), depth_methylation_summary_table)
  return(depth_methylation_summary_table)
}

###########################################################################
###### perform functions
##### PCA
setDT(ecoli_condition_motif_filter)
ecoli_4mC_5mC_6mA_position_combine_summary <- summary_table(ecoli_condition_motif_filter)
ecoli_4mC_5mC_6mA_position_combine_summary_table_wider <- summary_table_wider(ecoli_4mC_5mC_6mA_position_combine_summary)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table <- summary_cor_table_na_remove(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean <- removeZeroVar2(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table)
ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean <- summary_wider_clean(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider, ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean)
ecoli_methyl_pca_res <- prcomp(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean, scale. = T)

##### t-SNE
ecoli_condition_motif_summary <- summary_generation_replicate(ecoli_condition_motif_filter)
ecoli_condition_motif_methyl_corr_table <- corr_table_generate_replicate(ecoli_condition_motif_summary)

data_tsne <- tibble(perplexities = c(2, 4, 6, 8, 10), seed=c(1727, 1727, 1727, 1727, 1727))
data_tsne <- data_tsne %>% 
  mutate(
    TSNE = map2(perplexities, seed, ~{
      set.seed(.y)
      Rtsne(as.matrix(ecoli_condition_motif_methyl_corr_table[,-c(1:3)]), check_duplicates = FALSE, dims=3, PCA=F, theta = 0, perplexity=.x, max_iter=2000)}))

for (i in 1:nrow(data_tsne)){
  x = data_tsne$perplexities[[i]]
  assign(paste0("data_tsne_", x),
         tibble(
           x = data_tsne$TSNE[[i]]$Y[,1],
           y = data_tsne$TSNE[[i]]$Y[,2],
           z = data_tsne$TSNE[[i]]$Y[,3],
           perplexity = data_tsne$perplexities[[i]],
           seed = data_tsne$seed[[i]],
           condition = ecoli_condition_motif_methyl_corr_table$condition_short,
           replicate=ecoli_condition_motif_methyl_corr_table$replicate,
           phase=ecoli_condition_motif_methyl_corr_table$phase
         )
  )
}

###########################################################################
###### visualization
##### PCA
autoplot(ecoli_methyl_pca_res, data=ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean, 
         x = 1, y = 2,
         colour = "condition_short", size=3, shape = "phase", alpha=0.9) +
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  scale_shape_manual("", breaks = c("exponential", "stationary"),
                     values = c(16, 17)) + 
  labs(shape="Phase", colour="Condition") + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        legend.position="none") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

##### t-SNE
ggplot(data_tsne_4, aes(x=y, y=z, color=condition, label=replicate, shape=phase)) + 
  geom_point(size=5, alpha=0.85) +
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  theme_light() +
  labs(x="t-SNE2", y="t-SNE3", shape="Phase") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))


