library(data.table)
library(ggplot2)
library(tidyverse)
library(rstatix)
library(ggpubr)

###########################################################################
###### read files
##### these are the files generated by modkit pileup
setwd("")
ecoli_condition_motif <- fread("ecoli_condition_pileup_motif_focus_combine.bed", sep="\t", header = T)
options(scipen=999)

ecoli_condition_motif_filter <- ecoli_condition_motif[ecoli_condition_motif$valid_coverage>=20,]

###########################################################################
###### data filtering
ecoli_condition_motif_filter <- ecoli_condition_motif_filter %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage)

ecoli_condition_motif_filter <- ecoli_condition_motif_filter[ecoli_condition_motif_filter$modified_base_code=="m" | ecoli_condition_motif_filter$modified_base_code=="21839" | ecoli_condition_motif_filter$modified_base_code=="a",]

name_change_list <- list("37_degree"="37", "42_degree"="42", "acetic_acid"="ACE", "acetic_reverse"="RE", "3_Nacl"="TNA", "paraffin"="PA")
name_change_list_unlist <- unlist(name_change_list)

ecoli_condition_motif_filter$condition_short <- name_change_list_unlist[ecoli_condition_motif_filter$condition]

###########################################################################
###### statistics
ecoli_position_filter_genome_wide <- ecoli_condition_motif_filter %>%
  group_by(motif, modified_base_code, phase, condition_short, replicate) %>%
  summarise(modified_fraction=100*sum(modified_number)/sum(valid_coverage),
            unmodified_fraction=100-modified_fraction,
            .groups = "drop") %>%
  mutate(genus="Escherichia")

ecoli_motif_filter_phase_compare <- ecoli_position_filter_genome_wide %>%
  group_by(genus, condition_short, motif) %>%
  t_test(., modified_fraction ~ phase, paired = T) %>%
  add_significance() %>%
  add_xy_position(x="condition_short", dodge = 0.8, step.increase=0.05)

###########################################################################
###### visualization
ggplot(ecoli_position_filter_genome_wide, aes(x=condition_short, y=modified_fraction)) +
  facet_grid(vars(motif), scales = "free") +
  geom_boxplot(aes(color=phase), alpha=0.8) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(ecoli_motif_filter_phase_compare, hide.ns = TRUE,
                     label = "{p.signif}", size=5, bracket.size=0.8) +
  labs(y="Modified fraction (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 20),
        axis.title.x = element_blank(),
        legend.position = "none",
        strip.background = element_blank())

