library(data.table)
library(ggplot2)
library(tidyverse)
library(rstatix)
library(ggpubr)

###########################################################################
###### read files
##### these are the files generated by modkit pileup
setwd("")
ecoli_m4C_position <- fread("ecoli_condition_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
ecoli_m5C_position <- fread("ecoli_condition_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
ecoli_m6A_position <- fread("ecoli_condition_primary_pileup_combine_m6a.bed",sep="\t", header=TRUE)

ecoli_m4C_position_filter <- ecoli_m4C_position[ecoli_m4C_position$valid_coverage>=20,]
ecoli_m6A_position_filter <- ecoli_m6A_position[ecoli_m6A_position$valid_coverage>=20,]
ecoli_m5C_position_filter <- ecoli_m5C_position[ecoli_m5C_position$valid_coverage>=20,]

ecoli_genome_slide <- fread("GCF_000008865.2_ASM886v2_windows_10kb.bed", sep="\t", header = F)
colnames(ecoli_genome_slide) <- c("chromosome", "start", "end")

options(scipen=999)

ecoli_m6A_position_filter$modified_base_code[ecoli_m6A_position_filter$modified_base_code=="a"] <- "m6A" 
ecoli_m6A_position_filter <- ecoli_m6A_position_filter%>%
  subset(modified_base_code=="m6A")
ecoli_m4C_position_filter$modified_base_code[ecoli_m4C_position_filter$modified_base_code=="21839"] <- "m4C" 
ecoli_m4C_position_filter <- ecoli_m4C_position_filter%>%
  subset(modified_base_code=="m4C")
ecoli_m5C_position_filter$modified_base_code[ecoli_m5C_position_filter$modified_base_code=="m"] <- "m5C" 
ecoli_m5C_position_filter <- ecoli_m5C_position_filter%>%
  subset(modified_base_code=="m5C")

rm(ecoli_m4C_position, ecoli_m5C_position, ecoli_m6A_position)

###########################################################################
###### function blocks
##### 10-kb window
windows_methyl_form <- function(genome_slide_bed, filter_pileup_file) {
  fraction_modified_windows <- as.data.frame(matrix(nrow=0, ncol = 10))
  colnames(fraction_modified_windows) <- c("chrom", "start", "end", "modified_base_code", "condition", "phase", "replicate",
                                           "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  
  replicate_name_list <- unique(filter_pileup_file$replicate)
  inter_addition_form <- as.data.frame(matrix(nrow=0, ncol = 10))
  colnames(inter_addition_form) <- c("chrom", "start", "end", "modified_base_code", "condition", "phase", "replicate",
                                     "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  inter_addition_form_final <- as.data.frame(matrix(nrow=0, ncol = 10))
  colnames(inter_addition_form_final) <- c("chrom", "start", "end", "condition", "phase", "modified_base_code","replicate",
                                           "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  
  n_iter <- length(seq_len(nrow(genome_slide_bed)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(genome_slide_bed))){
    start_label <- as.integer(genome_slide_bed[i, "start"])
    end_label <- as.integer(genome_slide_bed[i, "end"])
    chromosome <- as.character(genome_slide_bed[i, "chromosome"])
    modified_base_code <- as.character(unique(filter_pileup_file$modified_base_code))
    
    inter_form <- subset(filter_pileup_file,
                         filter_pileup_file$start >= start_label & filter_pileup_file$end < end_label & filter_pileup_file$chrom == chromosome)
    
    inter_form_summary <- inter_form %>%
      group_by(chrom, modified_base_code, condition, phase, replicate) %>%
      summarise(sum_valid_coverage = sum(valid_coverage),
                sum_modified_number = sum(modified_number), .groups = "drop")
    inter_form_summary <- inter_form_summary %>%
      mutate(fraction_modified = 100*sum_modified_number/sum_valid_coverage)
    
    inter_form_summary$start <- start_label
    inter_form_summary$end <- end_label
    
    fraction_modified_windows <- rbind(fraction_modified_windows, inter_form_summary)
    
    setTxtProgressBar(pb, i)
  }
  cat("\n this is the way")
  close(pb) # Close the connection
  return(fraction_modified_windows)
}

##### identify mutual regions among replicates
common_replicate <- function(position_filter) {
  position_filter <- position_filter %>%
    mutate(replicate_start_end=paste(replicate, chrom, start, end, sep="_"))
  
  replicate_37_exp <- unique(position_filter[position_filter$condition=="37_degree" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_37_sta <- unique(position_filter[position_filter$condition=="37_degree" & position_filter$phase=="stationary",]$replicate_start_end)
  
  replicate_42_exp <- unique(position_filter[position_filter$condition=="42_degree" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_42_sta <- unique(position_filter[position_filter$condition=="42_degree" & position_filter$phase=="stationary",]$replicate_start_end)
  
  replicate_ace_exp <- unique(position_filter[position_filter$condition=="acetic_acid" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_ace_sta <- unique(position_filter[position_filter$condition=="acetic_acid" & position_filter$phase=="stationary",]$replicate_start_end)
  
  replicate_pa_exp <- unique(position_filter[position_filter$condition=="paraffin" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_pa_sta <- unique(position_filter[position_filter$condition=="paraffin" & position_filter$phase=="stationary",]$replicate_start_end)
  
  replicate_re_exp <- unique(position_filter[position_filter$condition=="acetic_reverse" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_re_sta <- unique(position_filter[position_filter$condition=="acetic_reverse" & position_filter$phase=="stationary",]$replicate_start_end)
  
  replicate_tna_exp <- unique(position_filter[position_filter$condition=="3_Nacl" & position_filter$phase=="exponential",]$replicate_start_end)
  replicate_tna_sta <- unique(position_filter[position_filter$condition=="3_Nacl" & position_filter$phase=="stationary",]$replicate_start_end)
  
  
  compared_list <- list(replicate_37_exp, replicate_37_sta,
                        replicate_42_exp, replicate_42_sta,
                        replicate_ace_exp, replicate_ace_sta,
                        replicate_pa_exp, replicate_pa_sta,
                        replicate_re_exp, replicate_re_sta,
                        replicate_tna_exp, replicate_tna_sta)
  
  common_replicates <- Reduce(intersect, compared_list)
  common_replicates_vec <- as.vector(unlist(common_replicates))
  print(length(common_replicates_vec))
  # common_replicates <- intersect(exp_replicate, sta_replicate, 
  #                                replicate_37, replicate_42, replicate_ace,
  #                                replicate_pa, replicate_re, replicate_tna)
  
  position_filter_common <- position_filter %>%
    filter(replicate_start_end %in% common_replicates)
  
  return(position_filter_common)
}

###########################################################################
###### use functions to perform analysis
##### create 10-kb window pileup file
m4c_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m4C_position_filter)
m5c_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m5C_position_filter)
m6a_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m6A_position_filter)

##### identify mutual regions
m6a_sliding_windows_common <- common_replicate(m4c_sliding_windows)
m4c_sliding_windows_common <- common_replicate(m5c_sliding_windows)
m5c_sliding_windows_common <- common_replicate(m6a_sliding_windows)

ecoli_m6a_m4c_m5c_sliding_windows_combine <- rbind(m6a_sliding_windows_common, m4c_sliding_windows_common, m5c_sliding_windows_common)

name_change_list <- list("37_degree"="37", "42_degree"="42", "acetic_acid"="ACE", "acetic_reverse"="RE", "3_Nacl"="TNA", "paraffin"="PA")
name_change_list_unlist <- unlist(name_change_list)

ecoli_m6a_m4c_m5c_sliding_windows_combine$condition_short <- name_change_list_unlist[ecoli_m6a_m4c_m5c_sliding_windows_combine$condition]

##### statistics
m6a_m4c_m5c_sliding_windows_combine_summary_block <- ecoli_m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(chrom, modified_base_code, condition, phase, start, end) %>%
  summarise(mean_fraction_modified = mean(fraction_modified),
            sd_fraction_modified = sd(fraction_modified), 
            mean_modified_number=mean(sum_modified_number), 
            sd_modified_number=sd(sum_modified_number), .groups = "drop")

m4c_m5c_sliding_windows_combine_summary <- ecoli_m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(modified_base_code, condition, phase) %>%
  summarise(mean_fraction_modified = mean(fraction_modified),
            sd_fraction_modified = sd(fraction_modified), 
            mean_modified_number=mean(sum_modified_number), 
            sd_modified_number=sd(sum_modified_number), .groups = "drop")

fraction_modified_windows_phase_compare <- ecoli_m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(modified_base_code, condition_short) %>%
  t_test(data = ., fraction_modified ~ phase, paired = T) %>%
  add_significance() %>%
  add_xy_position(x="condition_short", dodge = 0.8)

fraction_modified_windows_condition_compare <- ecoli_m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(modified_base_code, phase) %>%
  t_test(data = ., fraction_modified ~ condition_short, paired = F) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  add_xy_position(x="condition_short", dodge = 0.8, step.increase=1)

###########################################################################
###### visualization
ggplot(ecoli_m6a_m4c_m5c_sliding_windows_combine, aes(x=condition_short,y=fraction_modified)) +
  facet_grid(vars(modified_base_code), scales="free") +
  geom_boxplot(aes(color=phase), alpha=0.8, outlier.size=1) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(fraction_modified_windows_phase_compare, hide.ns = TRUE,
                     label = "{p.signif}", size=5, bracket.size=0.8) +
  labs(y="Segmental modified fraction (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 20),
        legend.position = "none",
        strip.background = element_blank())
