library(ggplot2)
library(tidyverse)
library(data.table)
library(grid)
library(glue)
library(janitor)
library(rstatix)
library(ggpubr)
library(patchwork)
library(cowplot)

###########################################################################
###### read files
##### these are the files generated by modkit dmr and dmr R scripts
setwd("")
condition_gene_methyl_position <- fread("condition_gene_methyl_position_combine.tsv", sep = "\t", header = T)
condition_nonregulatory_methyl_position <- fread("condition_gene_methyl_position_nonregulatory_combine.tsv", sep = "\t", header = T)

phase_gene_methyl_position <- fread("phase_gene_methyl_position_combine.tsv", sep = "\t", header = T)
phase_nonregulatory_methyl_position <- fread("phase_gene_methyl_position_nonregulatory_combine.tsv", sep = "\t", header = T)

shared_gene_phase<- fread("shared_gene_phase_under_condition.tsv", sep = "\t", header = F)

gene_annotation <- fread("GCF_000008865.2_ASM886v2_genomic_gene.tsv", sep="\t", header=F)
colnames(gene_annotation) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")

ecoli_nonregulate <- fread("GCF_000008865.2_ASM886v2_genomic_nonregulatory.bed", sep="\t", header = F)
colnames(ecoli_nonregulate) <- c("seqname", "start", "end")
options(scipen=999)

###########################################################################
###### read files
condition_gene_methyl_position_distinct <- condition_gene_methyl_position %>%
  group_by(chrom, strand, modified_base_code, phase, groups, region) %>%
  distinct(start, end) %>%
  filter(str_detect(groups, "^37")) %>%
  mutate(comparison_group=gsub("37_", "37_vs_", groups))

condition_nonregulatory_methyl_position_distinct <- condition_nonregulatory_methyl_position %>%
  group_by(chrom, strand, modified_base_code, phase, groups, region) %>%
  distinct(start, end) %>%
  filter(str_detect(groups, "^37")) %>%
  mutate(comparison_group=gsub("37_", "37_vs_", groups))

phase_gene_methyl_position_distinct <- phase_gene_methyl_position %>%
  group_by(chrom, strand, modified_base_code, condition, groups, region) %>%
  distinct(start, end)

phase_nonregulatory_methyl_position_distinct <- phase_nonregulatory_methyl_position %>%
  group_by(chrom, strand, modified_base_code, condition, groups, region) %>%
  distinct(start, end)

condition_metyhl_position_distinct <- rbind(condition_gene_methyl_position_distinct, condition_nonregulatory_methyl_position_distinct) %>%
  mutate(chrom_end_strand_modified_base_code=paste(chrom, end, strand, modified_base_code, sep = "_"))

phase_metyhl_position_distinct <- rbind(phase_gene_methyl_position_distinct, phase_nonregulatory_methyl_position_distinct) %>%
  mutate(chrom_end_strand_modified_base_code=paste(chrom, end, strand, modified_base_code, sep = "_"))

name_change_list <- list("37_degree"="37", "42_degree"="42", "acetic_acid"="ACE", "acetic_reverse"="RE", "3_Nacl"="TNA", "paraffin"="PA")
name_change_list_unlist <- unlist(name_change_list)

phase_metyhl_position_distinct$condition_short <- name_change_list_unlist[phase_metyhl_position_distinct$condition]

###########################################################################
###### statistics
#### summary and t-test
GC_content <- 0.505
genome_size <- 5498578+3306+92721

GC_bases <- genome_size*GC_content
AC_bases <- genome_size*(1-GC_content)

condition_metyhl_position_distinct_summary <- condition_metyhl_position_distinct %>%
  group_by(modified_base_code, phase, comparison_group) %>%
  summarise(count=n(), .groups = "drop") %>%
  mutate(normalized_count = ifelse(modified_base_code=="m4C" | modified_base_code=="m5C", 
                                   100*count/GC_bases, 100*count/AC_bases))

phase_metyhl_position_distinct_summary <- phase_metyhl_position_distinct %>%
  group_by(modified_base_code, condition, condition_short, groups) %>%
  summarise(count=n(), .groups = "drop") %>%
  mutate(normalized_count = ifelse(modified_base_code=="m4C" | modified_base_code=="m5C", 
                                   100*count/GC_bases, 100*count/AC_bases))

condition_metyhl_position_distinct_phase_compare <- condition_metyhl_position_distinct_summary %>%
  group_by(modified_base_code) %>%
  t_test(data = ., normalized_count ~ phase, paired = T) %>%
  add_significance() %>%
  add_xy_position(x="modified_base_code", dodge = 0.8)

phase_metyhl_position_distinct_modified_base_compare <- phase_metyhl_position_distinct_summary %>%
  t_test(data = ., normalized_count ~ modified_base_code, paired = F) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  add_xy_position(x="modified_base_code", dodge = 0.8, step.increase = 0.05)

#### linear model
condition_metyhl_position_lm <- lm(normalized_count ~ comparison_group + phase + modified_base_code, data = condition_metyhl_position_distinct_summary)
condition_metyhl_position_df <- as.data.frame(anova(condition_metyhl_position_lm))
condition_metyhl_position_df$term <- rownames(condition_metyhl_position_df)
rownames(condition_metyhl_position_df) <- NULL

phase_metyhl_position_distinct_summary$condition_short <- as.character(phase_metyhl_position_distinct_summary$condition_short)
phase_metyhl_position_lm <- lm(normalized_count ~ condition_short + modified_base_code, data = phase_metyhl_position_distinct_summary)
phase_metyhl_position_df <- as.data.frame(anova(phase_metyhl_position_lm))
phase_metyhl_position_df$term <- rownames(phase_metyhl_position_df)
rownames(phase_metyhl_position_df) <- NULL

###########################################################################
###### visualization
##### density
density_phase <- ggplot() +
  geom_density(data=phase_metyhl_position_distinct, aes(x=end, color=condition_short), alpha=0.8) +
  geom_density(data = diff_gene_list, aes(x = end), linetype = "dashed", color = "black") +
  labs(x="Genomic position") + 
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 20),
        strip.text = element_text(color="black"),
        legend.position = "bottom",
        strip.background = element_blank())

density_condition <- ggplot() +
  geom_density(data = condition_metyhl_position_distinct, aes(x = end, color = comparison_group), alpha=0.8) +
  geom_density(data = diff_gene_list, aes(x = end), linetype = "dashed", color = "black") +
  facet_grid(vars(phase)) +
  labs(x="Genomic position") + 
  scale_color_manual("Comparison group", breaks = c("37_vs_TNA", "37_vs_42", "37_vs_ACE", "37_vs_RE", "37_vs_PA"),
                     values = c("#a20b52", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 20),
        strip.text = element_text(color="black"),
        legend.position = "bottom",
        strip.background = element_blank()) +
  guides(colour = guide_legend(nrow = 2))

density_phase <- density_phase +
  labs(tag="A") +
  theme(plot.tag = element_text(face = "bold", size = 25))

density_condition <- density_condition +
  labs(tag="B") +
  theme(plot.tag = element_text(face = "bold", size = 25))

wrap_plots(density_phase, density_condition, nrow = 2, heights = c(0.6,1))


##### boxplot
condition_phase_compare <- ggplot(condition_metyhl_position_distinct_summary,
                                  aes(x = modified_base_code, 
                                      y = normalized_count)) +
  geom_boxplot(width = 0.5, aes(colour = phase), outlier.shape = NA) +
  geom_point(aes(fill = comparison_group, group = phase),
             alpha = 1, size = 2, shape = 21,
             position = position_dodge(width = 0.5)) +
  scale_y_continuous(transform = "log1p",
                     limits = c(0, NA)) +
  scale_fill_manual("Comparison group", breaks = c("37_vs_TNA", "37_vs_42", "37_vs_ACE", "37_vs_RE", "37_vs_PA"),
                    values = c("#a20b52", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(condition_metyhl_position_distinct_phase_compare, hide.ns = T,
                     label = "{p.signif}", size=5, bracket.size=0.5) +
  labs(y="Normalized sites", title ="Culture Conditions") +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        plot.title = element_text(face = "bold")) +
  theme(text = element_text(size = 20),
        strip.text = element_text(color="black"),
        legend.position = "bottom",
        legend.box.just= "centre",
        plot.title= element_text(hjust=0.5, size=20),
        strip.background = element_blank()) +
  guides(fill=guide_legend(nrow=3, byrow=TRUE),
         color=guide_legend(nrow=2, byrow=TRUE))

phase_base_compare <- ggplot(phase_metyhl_position_distinct_summary, aes(x=modified_base_code, y=normalized_count, color=condition_short)) +
  geom_boxplot(width = 0.3, color="#808080") +
  geom_point(alpha=0.9, size=2) +
  scale_y_continuous(transform = "log1p",
                     limits = c(0, NA)) +
  scale_color_manual("Condition", breaks = c("TNA", "37", "42", "ACE", "RE", "PA"),
                     values = c("#a20b52", "#bdbdbd", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f")) + 
  stat_pvalue_manual(phase_metyhl_position_distinct_modified_base_compare, hide.ns = TRUE,
                     label = "{p.adj.signif}", size=6, bracket.size=0.8, step.increase = 0) +
  labs(y="Normalized sites", title="Growth Phase Transition") +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        plot.title = element_text(face = "bold", size=20)) +
  theme(text = element_text(size = 20),
        strip.text = element_text(color="black"),
        legend.position = "bottom",
        plot.title= element_text(hjust=0.5),
        strip.background = element_blank())

condition_phase_compare <- condition_phase_compare +
  labs(tag="B") +
  theme(plot.tag = element_text(face = "bold", size = 25))

phase_base_compare <- phase_base_compare +
  labs(tag="A") +
  theme(plot.tag = element_text(face = "bold", size = 25))

plot_grid(phase_base_compare, condition_phase_compare, ncol = 2, rel_widths = c(0.7, 1))
