library(data.table)
library(ggplot2)
library(igraph)
library(ggraph)
library(tidygraph)
library(patchwork)
library(ggrepel)
library(glue)

######################################################################################################
###### function blocks
##### Function to read annotation files
read_gene_files <- function(pat, dir) {
  filenames <- list.files(dir, pattern = pat, full.names=F)
  ldf <- lapply(filenames, function(f) {
    fread(glue("{dir}/{f}"), sep = ",", header = T)
  })
  names(ldf) <- sub("\\_network_.*.csv$", "", filenames)
  return(ldf)
}

assign_variable <- function(read_gene_files) {
  for (name in names(read_gene_files)){
    assign(name, read_gene_files[[name]], envir = .GlobalEnv)
  }
}

network_graph <- function(nodes, edges, title_name, seed=10) {
  nodes$size <- as.numeric(nodes$size)
  
  ig <- graph_from_data_frame(d = edges, 
                              vertices = nodes %>% select(-shape, -color), 
                              directed = FALSE)
  
  ig_communities <- cluster_edge_betweenness(ig)
  V(ig)$group <- ig_communities$membership
  
  set.seed(seed)
  ig_graph <- ggraph(ig, layout = "circle") +  # force-directed layout
    geom_edge_link(aes(width = width), alpha = 0.06, lineend="round", linejoin = "round") +
    geom_node_point(aes(size=size, fill=as.factor(group)), alpha=0.8, shape=21) + 
    scale_fill_manual(values = c("#a20b52", "#3d7fd1", "#755f8b", "#e66101", "#ffd92f", "#328cb0", 
                                 "#d93b8e", "#bae1ff", "#999999", "#ffbf7f", "#e5c494", "#7da3c1")) +
    scale_size_continuous(range = c(4, 10)) +
    geom_node_text(aes(label = label), hjust = 0.1, repel = TRUE, size = 3.5) +
    theme_void() +
    labs(title = title_name) +
    theme(legend.position = "none",
          plot.title = element_text(hjust = 0.5, vjust = 1, size=20, face = "bold"))
  
  return(ig_graph)
}

for (name in condition_name){
  split_string <- unlist(strsplit(name, "_"))
  graph_title <- paste(split_string[2], split_string[3], split_string[4], sep = "_")
  
  assign(name, network_graph(nodes[[name]], edges[[name]], graph_title, 20), envir = .GlobalEnv)
  # network_graph(nodes[[name]], edges[[name]], 10)
}

######################################################################################################
###### use functions to perform analysis
##### these are files generated by ShinyGO
setwd("")
dir <- ""

edges <- read_gene_files("^distinct_37.*under_.*_edges.csv$", dir)
nodes <- read_gene_files("^distinct_37.*under_.*_nodes.csv$", dir)

condition_name <- sub("\\_network_.*$", "", names(edges))


######################################################################################################
##### visualization
distinct_37_vs_42_under_exp <- distinct_37_vs_42_under_exp +
  labs(tag="A") +
  theme(plot.tag = element_text(face = "bold", size = 25))
distinct_37_vs_42_under_sta <- distinct_37_vs_42_under_sta +
  labs(tag="A") +
  theme(plot.tag = element_text(face = "bold", size = 25))

distinct_37_vs_ACE_under_exp <- distinct_37_vs_ACE_under_exp +
  labs(tag="B") +
  theme(plot.tag = element_text(face = "bold", size = 25))
distinct_37_vs_ACE_under_sta <- distinct_37_vs_ACE_under_sta +
  labs(tag="B") +
  theme(plot.tag = element_text(face = "bold", size = 25))

distinct_37_vs_PA_under_exp <- distinct_37_vs_PA_under_exp +
  labs(tag="C") +
  theme(plot.tag = element_text(face = "bold", size = 25))
distinct_37_vs_PA_under_sta <- distinct_37_vs_PA_under_sta +
  labs(tag="C") +
  theme(plot.tag = element_text(face = "bold", size = 25))

distinct_37_vs_RE_under_exp <- distinct_37_vs_RE_under_exp +
  labs(tag="D") +
  theme(plot.tag = element_text(face = "bold", size = 25))
distinct_37_vs_RE_under_sta <- distinct_37_vs_RE_under_sta +
  labs(tag="D") +
  theme(plot.tag = element_text(face = "bold", size = 25))

distinct_37_vs_TNA_under_exp <- distinct_37_vs_TNA_under_exp +
  labs(tag="E") +
  theme(plot.tag = element_text(face = "bold", size = 25))
distinct_37_vs_TNA_under_sta <- distinct_37_vs_TNA_under_sta +
  labs(tag="E") +
  theme(plot.tag = element_text(face = "bold", size = 25))


distinct_37_vs_42_under_exp + distinct_37_vs_ACE_under_exp + distinct_37_vs_PA_under_exp + 
  distinct_37_vs_RE_under_exp + distinct_37_vs_TNA_under_exp + plot_layout(ncol=3, nrow = 2)


distinct_37_vs_42_under_sta + distinct_37_vs_ACE_under_sta + distinct_37_vs_PA_under_sta + 
  distinct_37_vs_RE_under_sta + distinct_37_vs_TNA_under_sta + plot_layout(ncol=3, nrow = 2)
