library(data.table)
library(ggplot2)
library(tidyverse)
library(ggvenn)
library(janitor)
library(ggVennDiagram)
library(patchwork)
library(cowplot)

###########################################################################
###### read files
##### these are the files generated by modkit dmr and dmr R scripts
setwd("")

origin_valid_phase_gene <- fread("origin_valid_phase_gene_pvalue.tsv", sep = "\t", header = T)
origin_valid_condition_gene <- fread("origin_valid_condition_gene_pvalue.tsv", sep = "\t", header = T)

ecoli_gene_body <- fread("GCF_000008865.2_ASM886v2_genomic_gene.tsv", sep="\t", header = F)
colnames(ecoli_gene_body) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")

###########################################################################
###### data manipulation
origin_valid_condition_gene$group[origin_valid_condition_gene$group == "ACEV_TNAV"] <- "ACE_TNA"

origin_valid_phase_gene$condition[origin_valid_phase_gene$condition == "ACEV"] <- "ACE"
origin_valid_phase_gene$condition[origin_valid_phase_gene$condition == "TNAV"] <- "TNA"
origin_valid_phase_gene$group <- gsub(".*", "exponential_vs_stationary", origin_valid_phase_gene$group)

origin_valid_phase_gene_clean <- origin_valid_phase_gene %>%
  group_by(id, condition, set, group) %>%
  slice_min(., balanced_map_pvalue) %>%
  distinct(id, .keep_all = T)

origin_valid_phase_gene_clean[duplicated(origin_valid_phase_gene_clean$id),]

origin_valid_condition_gene_clean <- origin_valid_condition_gene %>%
  group_by(id, group, set, phase) %>%
  slice_min(., balanced_map_pvalue) %>%
  distinct(id, .keep_all = T) %>%
  mutate(comparison_group=gsub("ACE_", "ACE_vs_", group))

origin_valid_condition_gene_clean[duplicated(origin_valid_condition_gene_clean$id),]
origin_valid_condition_gene[duplicated(origin_valid_condition_gene$id),]


###########################################################################
###### functions for analysis
##### linear correlation
get_formula <- function(model){
  formula <-
    paste0("y ~ ", round(coefficients(model)[1],2), "+", 
           paste(sprintf("%.2f * %s", 
                         coefficients(model)[-1],  
                         # names(coefficients(model)[-1]),
                         "x"), 
                 collapse=""
           )
    )
  r2 <- round(summary(model)$r.squared, 5)
  p <- as.numeric(summary(model)$coefficients[, 4]["trans_pvalue_origin"])
  p_short <- ifelse(p<=0.001, "p<0.001", 
                    ifelse(p<=0.01, "p<0.01",
                           ifelse(p<=0.05, "p<0.05", "ns")))
  formula_r <- paste0(formula, ", R2=", r2, ", ", p_short)
  return(formula_r)
}

linear_corr_graph_phase <- function(dataset, con, linear_model){
  coeff <- coefficients(linear_model)         
  intercept <- coeff[1]
  slope <- coeff[2]
  
  graph <- ggplot(data=dataset[dataset$condition==con,], aes(x=trans_pvalue_origin, y=trans_pvalue_validation, color=trend)) +
    facet_wrap(vars(group, condition)) +
    geom_point(alpha=0.6, size=1) +
    geom_abline(intercept = intercept, slope = slope, color="black", 
                linetype="longdash", size=1) + 
    annotate(geom='text', x=3, y=15, label=get_formula(linear_model), size=4) +
    theme_light() +
    labs(x= "Original", y="Validation", color="Significance") +
    scale_color_manual(values = c("#a20b52", "#3d7fd1", "#755f8b", "#7da3c1")) +
    theme(axis.title = element_text(face = "bold"),
          legend.position = "none",
          legend.title = element_text(face="bold"),
          strip.background = element_blank(),
          strip.text = element_text(colour = "black")) +
    theme(text = element_text(size=20)) +
    guides(colour = guide_legend(override.aes = list(size=3, alpha=1)))
  
  return(graph)
}

linear_corr_graph_condition <- function(dataset, growth_phase, linear_model){
  coeff <- coefficients(linear_model)         
  intercept <- coeff[1]
  slope <- coeff[2]
  
  graph <- ggplot(data=dataset[dataset$phase==growth_phase,], aes(x=trans_pvalue_origin, y=trans_pvalue_validation, color=trend)) +
    facet_wrap(vars(comparison_group, phase)) +
    geom_point(alpha=0.6, size=1) +
    geom_abline(intercept = intercept, slope = slope, color="black", 
                linetype="longdash", size=1) + 
    annotate(geom='text', x=2, y=4, label=get_formula(linear_model), size=4) +
    theme_light() +
    labs(x= "Original", y="Validation", color="Significance") +
    scale_color_manual(values = c("#a20b52", "#3d7fd1", "#755f8b", "#7da3c1")) +
    theme(axis.title = element_text(face = "bold"),
          legend.position = "none",
          legend.title = element_text(face="bold"),
          strip.background = element_blank(),
          strip.text = element_text(colour = "black")) +
    theme(text = element_text(size=20)) +
    guides(colour = guide_legend(override.aes = list(size=3, alpha=1)))
  
  return(graph)
}

##### venn correlation
gene_id_element_list_condition <- function(df, growth_phase){
  gene_id_element_methylation <- list()
  
  df_filter <- df %>%
    filter(phase==growth_phase & differential=="yes") %>%
    group_by(comparison_group, set) %>%
    distinct(id) %>%
    summarise(gene_id_uniq = paste(unique(id), collapse = ","), .groups = "drop")
  
  for (i in seq_len(nrow(df_filter))) {
    group_id=as.character(df_filter[i, "set"])
    # print(group_id)
    gene_list=strsplit(as.vector(df_filter[["gene_id_uniq"]][i]), ",")
    gene_id_element_methylation[[group_id]] <- (unlist(gene_list))
  }
  return(gene_id_element_methylation)

}

gene_id_element_list_phase <- function(df, con){
  gene_id_element_methylation <- list()
  
  df_filter <- df %>%
    filter(condition==con & differential=="yes") %>%
    group_by(set) %>%
    distinct(id) %>%
    summarise(gene_id_uniq = paste(unique(id), collapse = ","), .groups = "drop")
  
  for (i in seq_len(nrow(df_filter))) {
    group_id=as.character(df_filter[i, "set"])

    gene_list=strsplit(as.vector(df_filter[["gene_id_uniq"]][i]), ",")
    gene_id_element_methylation[[group_id]] <- (unlist(gene_list))
  }
  return(gene_id_element_methylation)

}

venn_graph <- function(gene_id_list, title_name){
  gene_id_stack <- stack(gene_id_list)
  
  gene_id_stack_wider <- gene_id_stack %>%
    pivot_wider(names_from = values, values_from = values, id_cols = ind)
  
  gene_id_stack_wider[] <- lapply(gene_id_stack_wider, as.character)
  
  gene_id_stack_wider_long <- rbind(names(gene_id_stack_wider), gene_id_stack_wider) %>%
    t() %>%
    row_to_names(row_number = 1) %>%
    as.tibble()
  
  gene_id_stack_wider_long[,-1] <- lapply(gene_id_stack_wider_long[,-1], function(x) ifelse(is.na(x), FALSE, TRUE))
  
  venn <- ggplot(gene_id_stack_wider_long, aes(A=origin, B=validation)) +
    geom_venn(set_names = c("origin","validation"),
              stroke_size = 0.8,
              text_size = 4,
              show_percentage = T,
              fill_alpha = 0.55,
              auto_scale = F,
              fill_color = c("#328cb0", "#a20b52")) +
    theme_void() +
    labs(title = title_name) +
    coord_fixed() +
    theme(plot.title = element_text(hjust = 0.5, vjust = -10, size=18, face = "bold"))
  return(venn)
}


##### fisher exact test
fisher_exact_test <- function(gene_id_list, genome_size) {
  common <- length(intersect(gene_id_list[["origin"]], gene_id_list[["validation"]]))
  origin_unique <- length(setdiff(gene_id_list[["origin"]], gene_id_list[["validation"]]))
  valid_unique <- length(setdiff(gene_id_list[["validation"]], gene_id_list[["origin"]]))
  
  fisher_forms <- matrix(c(common, origin_unique, valid_unique, genome_size-common-origin_unique-valid_unique), nrow = 2)
  
  return_list <- list()
  return_list[[1]] <- fisher_forms
  return_list[[2]] <- fisher.test(fisher_forms, alternative = "greater")
  
  return(return_list)
}
######################################################
###### use functions to perform analysis
#### linear correltaion between datasets
### the following analysis only include genes with p-values in both validation and origin datasets.
origin_valid_condition_wider <- origin_valid_condition_gene_clean %>%
  pivot_wider(id_cols=c(id, comparison_group, phase), 
              names_from = set, values_from = balanced_map_pvalue)

origin_valid_condition_wider_clean <- origin_valid_condition_gene_clean %>%
  pivot_wider(id_cols=c(id, comparison_group, phase), 
              names_from = set, values_from = c(balanced_map_pvalue, cohen_h)) %>%
  na.omit() %>%
  mutate(trend=ifelse((balanced_map_pvalue_validation <= 0.05 & abs(cohen_h_validation) >= 0.2) & 
                        (balanced_map_pvalue_origin <= 0.05 & abs(cohen_h_origin) >= 0.2), "Both",
                      ifelse((balanced_map_pvalue_validation <= 0.05 & abs(cohen_h_validation) >= 0.2) & 
                               balanced_map_pvalue_origin > 0.05, "Validation only",
                             ifelse(balanced_map_pvalue_validation > 0.05 & 
                                      (balanced_map_pvalue_origin <= 0.05 & abs(cohen_h_origin) >= 0.2), "Original only", "None")))) %>%
  mutate(trans_pvalue_origin=-(log10(balanced_map_pvalue_origin)),
         trans_pvalue_validation=-(log10(balanced_map_pvalue_validation)))

origin_valid_phase_wider <- origin_valid_phase_gene_clean %>%
  pivot_wider(id_cols=c(id, condition), 
              names_from = set, values_from = balanced_map_pvalue)

origin_valid_phase_wider_clean <- origin_valid_phase_gene_clean %>%
  pivot_wider(id_cols=c(id, condition, group), 
              names_from = set, values_from = c(balanced_map_pvalue, cohen_h)) %>%
  na.omit() %>%
  mutate(trend=ifelse((balanced_map_pvalue_validation <= 0.05 & abs(cohen_h_validation) >= 0.2) & 
                        (balanced_map_pvalue_origin <= 0.05 & abs(cohen_h_origin) >= 0.2), "Both",
                      ifelse((balanced_map_pvalue_validation <= 0.05 & abs(cohen_h_validation) >= 0.2) & 
                               balanced_map_pvalue_origin > 0.05, "Validation only",
                             ifelse(balanced_map_pvalue_validation > 0.05 & 
                                      (balanced_map_pvalue_origin <= 0.05 & abs(cohen_h_origin) >= 0.2), "Original only", "None")))) %>%
  mutate(trans_pvalue_origin=-(log10(balanced_map_pvalue_origin)),
         trans_pvalue_validation=-(log10(balanced_map_pvalue_validation)))


ace_tna_exp <- lm(trans_pvalue_validation ~ trans_pvalue_origin, data=origin_valid_condition_wider_clean[origin_valid_condition_wider_clean$phase=="exponential",])
ace_tna_sta <- lm(trans_pvalue_validation ~ trans_pvalue_origin, data=origin_valid_condition_wider_clean[origin_valid_condition_wider_clean$phase=="stationary",])

exp_sta_ace <- lm(trans_pvalue_validation ~ trans_pvalue_origin, data=origin_valid_phase_wider_clean[origin_valid_phase_wider_clean$condition=="ACE",])
exp_sta_tna <- lm(trans_pvalue_validation ~ trans_pvalue_origin, data=origin_valid_phase_wider_clean[origin_valid_phase_wider_clean$condition=="TNA",])

######################################################
###### linear correlation visualization
exp_sta_ace_linear <- linear_corr_graph_phase(origin_valid_phase_wider_clean, "ACE", exp_sta_ace)
exp_sta_tna_linear <- linear_corr_graph_phase(origin_valid_phase_wider_clean, "TNA", exp_sta_tna)

ace_tna_exp_linear <- linear_corr_graph_condition(origin_valid_condition_wider_clean, "exponential", ace_tna_exp)
ace_tna_sta_linear <- linear_corr_graph_condition(origin_valid_condition_wider_clean, "stationary", ace_tna_sta)

exp_sta_ace_linear <- exp_sta_ace_linear +
  labs(tag="A") +
  theme(plot.tag = element_text(face = "bold", size = 22))
exp_sta_ace_linear

exp_sta_tna_linear <- exp_sta_tna_linear +
  labs(tag="B") +
  theme(plot.tag = element_text(face = "bold", size = 22))
exp_sta_tna_linear

ace_tna_exp_linear <- ace_tna_exp_linear +
  labs(tag="C") +
  theme(plot.tag = element_text(face = "bold", size = 22))
ace_tna_exp_linear

ace_tna_sta_linear <- ace_tna_sta_linear +
  labs(tag="D") +
  theme(plot.tag = element_text(face = "bold", size = 22))
ace_tna_sta_linear

linear_graph <- wrap_plots(exp_sta_ace_linear, exp_sta_tna_linear, ace_tna_exp_linear, ace_tna_sta_linear,
                           nrow = 2, ncol = 2, widths = c(1, 1))

linear_legend <- get_legend(exp_sta_ace_linear + theme(legend.position="bottom", legend.box.just = "right",
                                                       legend.title = element_text(face = "bold", size = 20)))
linear_graph
plot_grid(linear_graph, linear_legend, ncol = 1, nrow = 2, rel_heights = c(1, 0.1))

######################################################
#### venn correltaion between datasets
gene_condition_exp <- gene_id_element_list_condition(origin_valid_condition_gene_clean, "exponential")
gene_condition_sta <- gene_id_element_list_condition(origin_valid_condition_gene_clean, "stationary")

gene_phase_ace <- gene_id_element_list_phase(origin_valid_phase_gene_clean, "ACE")
gene_phase_tna <- gene_id_element_list_phase(origin_valid_phase_gene_clean, "TNA")

#### venn graph visualization
gene_condition_exp_venn <- venn_graph(gene_condition_exp, "exponential")
gene_condition_sta_venn <- venn_graph(gene_condition_sta, "stationary") 

gene_phase_ace_venn <- venn_graph(gene_phase_ace, "ACE")
gene_phase_tna_venn <- venn_graph(gene_phase_tna, "TNA")

gene_condition_exp_venn <- gene_condition_exp_venn +
  labs(tag = "A") +
  theme(plot.tag = element_text(size=23, face="bold")) + 
  coord_cartesian(clip = "on")

gene_condition_sta_venn <- gene_condition_sta_venn +
  labs(tag = "B") +
  theme(plot.tag = element_text(size=23, face="bold")) + 
  coord_cartesian(clip = "on")

gene_phase_ace_venn <- gene_phase_ace_venn +
  labs(tag = "C") +
  theme(plot.tag = element_text(size=23, face="bold")) + 
  coord_cartesian(clip = "on")

gene_phase_tna_venn <- gene_phase_tna_venn +
  labs(tag = "D") +
  theme(plot.tag = element_text(size=23, face="bold")) + 
  coord_cartesian(clip = "on")

gene_condition_exp_venn + gene_condition_sta_venn + 
  gene_phase_ace_venn + gene_phase_tna_venn + plot_layout()

######################################################
#### fisher exact test for overlapping genes
gene_background_number <- length(ecoli_gene_body$id)

fisher_exact_test(gene_condition_exp, gene_background_number)[2]
fisher_exact_test(gene_condition_sta, gene_background_number)[2]

fisher_exact_test(gene_phase_ace, gene_background_number)[2]
fisher_exact_test(gene_phase_tna, gene_background_number)[2]


fisher_exact_test(gene_condition_exp, gene_background_number)[1]
fisher_exact_test(gene_condition_sta, gene_background_number)[1]

fisher_exact_test(gene_phase_ace, gene_background_number)[1]
fisher_exact_test(gene_phase_tna, gene_background_number)[1]
